### PR TITLE
Add locking during hardware selection

### PR DESCRIPTION
**Pull request by ptrivedi**
Synchronize the hardware selection and ownership update process among
different reconciler threads. To achieve this, add locking to make the operations
of picking up hardware and updating it's ownership atomic.
This helps avoid the race condition of same hardware being selected for different
machines.

Signed-off-by: Pooja Trivedi <tripooja@amazon.com>

## Why is this needed

Fixes: #

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by micahhausler** [comment]
@ptrivedi I thought the resolution for this was to use `.Update()` instead of `.Patch()` ? That way an update on an out-of-date object revision would fail, and whoever wins the race would succeed.

**Comment by ptrivedi** [comment]
> 

Maybe you're thinking of a different issue? This happens because the hardware selection and ownership-label update don't happen atomically and reconciler threads race. It is prior to the point of patch/update to update the hardware labels. @detiber and I had agreed on this being the best approach and we had extensively tested this out on AWS side during beta.

**Comment by micahhausler** [comment]
@ptrivedi `.Update()` should solve the race condition here, because which ever one wins the race wins, and whichever looses will have an old revision, so the update will fail

**Comment by chrisdoherty4** [comment]
Just to echo and elaborate on what Micah is saying: when you use an `Update` it replaces the object. While this is less preferred to an update because it doesn't have patch history it is _necessary_ for atomic operations. It works because the server checks the latest resource version with what you've submitted. If you're behind, you get rejected and have to retry. 

Worth pointing out this ties in with scheduling logic also.

**Pull request closed without merging**
