### PR TITLE
CAPT Playground

### PR DESCRIPTION
**Pull request by jacobweinstock**
## Description

WIP for creating a playground in which to use, learn, and test CAPT.

## Why is this needed

Fixes: #

## Checklist:

I have:

- [ ] updated the documentation and/or roadmap (if required)
- [ ] added unit or e2e tests
- [ ] provided instructions on how to upgrade

### CODE REVIEW

**Comment by chrisdoherty4** [comment]
Looking sharp, but I do feel like we should just script this. A lot of the Go code is boilerplate around command invocations as we talked about.

**Comment by jacobweinstock** [comment]
> Looking sharp, but I do feel like we should just script this. A lot of the Go code is boilerplate around command invocations as we talked about.

I'm open to discussing this. Here's my take. Its quite a bit nicer to work with Go for all the yaml creation than a shell script. A single binary is preferable too. I prefer working with Go around writing command, stdout, stderr to log a file than a script. For me, boilerplate in and of itself isnt a strong enough reason to move to shell. I'm keen to know more from your end. Thanks!

**Comment by chrisdoherty4** [comment]
@jacobweinstock Truthfully I glanced through the code and was keying off our last convo; you're in the thick of it, so if you have good reasons I'm good sticking with Go.

**Comment by jacobweinstock** [comment]
Going to have this be in the https://github.com/tinkerbell/playground repo instead of here. https://github.com/tinkerbell/playground/pull/191

**Pull request closed without merging**
